remote_theme: nextzlog/pafe
url: https://use.zlog.org
name: zLog令和版
icon: /images/zlog.png
lead: &desc Windowsで動作するコンテスト用ロギングソフトzLog令和版の機能を紹介しています。
desc: *desc
items:
- name: マニュアル
  href: /manual
  icon: fas fa-book
- name: プラグイン
  href: /plugins
  icon: fas fa-shopping-cart
- name: ダウンロード
  href: /downloads
  icon: fas fa-download
links:
- name: CFG/DAT
  href: http://ja6ycu.in.coocan.jp/ZLOG
- name: zLog.org
  href: https://zlog.org
- name: JR8PPG
  href: http://599010103.blog84.fc2.com
- name: 無線部開発班
  href: https://nextzlog.dev
jumps:
- name: マニュアル
  href: /manual
  icon: fas fa-book
- name: ダウンロード
  href: /downloads
  icon: fas fa-download
