on:
  push:
    branches:
    - 'master'
  schedule:
  - cron: '5 0 * * *'
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  actions: write
  pages: write
env:
  RELEASES: repos/jr8ppg/zlog/releases
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        mkdir -p _data
        gh api $RELEASES --paginate > _data/releases.json
        curl -o _data/market.json https://pkg.zlog.org/market.json
    - uses: actions/configure-pages@v5
    - uses: actions/jekyll-build-pages@v1
    - uses: actions/upload-pages-artifact@v3
  Publish:
    needs: Prepare
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/deploy-pages@v4
  Sustain:
    runs-on: ubuntu-latest
    steps:
    - run: gh workflow enable build.yaml
      env:
        GH_REPO: ${{github.repository}}
